name: pre-commit

on:
  workflow_call:

jobs:
  pre-commit:

    needs: cleanup

    runs-on: ubuntu-latest
      
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: pre-commit/action@v3.0.0